url: "lihan829.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Han Li" # the name of your site, e.g. ACME Corp.
description: "PhD student in Linguistics at Stony Brook University"
