title: Han Li
description:  PhD Candidate in Linguistics | Computational Phonology
theme: just-the-docs

url: "https://lihan829.github.io/"
favicon_ico: "/images/favicon.ico"




aux_links:
  GitHub: https://github.com/lihan829
  LinkedIn: https://www.linkedin.com/in/lihan61
  Google Scholar: https://scholar.google.com/citations?user=2_Fyp30AAAAJ&hl=en
  Email: mailto:han.li.4@stonybrook.edu


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
