title: Han Li's Homepage
description:  PhD Candidate in Linguistics | Computational Phonology
theme: just-the-docs

url: https://just-the-docs.github.io


aux_links:
  LinkedIn: https://www.linkedin.com/in/lihan61
  Google Scholar: https://scholar.google.com/citations?user=2_Fyp30AAAAJ&hl=en
  Email: mailto:han.li.4@stonybrook.edu
